(() => {
    const byId=id=>document.getElementById(id),overview=byId('overview'),play=byId('play'),board=byId('board'),result=byId('result'),score=byId('score');
    const C=GameCore;let storage;try{storage=localStorage;}catch(_){}
    const nextWord=C.wordDeck(GameWords,storage);let selected='',generation=0,opener=null,wordWins=0,mathLevel=1,focusLevel=1,sequenceLevel=1;const timers=new Set();
    const info={pairs:['Matching Pairs','Memory','Turn over two cards at a time. Find all eight pairs.'],words:['Word Scramble','Word power','Put the letters in order. A category and a hint can help.'],tiles:['Number Slide','Spatial thinking','Tap a highlighted tile next to the empty space, or swipe it into the space. No typing. Arrange 1–15 across each row.'],sudoku:['Sudoku','Logic','Choose your challenge. Fill each row, column and box without repeating a number.'],sequence:['Sequence Memory','Recall','Watch the highlighted shapes, then tap them in the same order.'],math:['Number Sense','Mental math','Ten little number challenges. Take all the time you need.'],focus:['Color Focus','Attention','Choose the color of the ink, rather than the word it spells.']};
    function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
    function button(text,action,cls=''){const b=element('button',text,cls);b.type='button';b.onclick=action;return b;}
    function chips(...texts){score.replaceChildren(...texts.map(text=>element('span',text,'chip')));}
    function clearTimers(){for(const timer of timers)clearTimeout(timer);timers.clear();}
    function later(action,ms){const current=generation,timer=setTimeout(()=>{timers.delete(timer);if(current===generation)action();},ms);timers.add(timer);}
    function delay(ms){return new Promise(resolve=>later(resolve,ms));}
    function say(text){result.textContent=text;}
    function controls(...buttons){const row=element('div',undefined,'controls');row.append(...buttons);return row;}
    function start(game){clearTimers();generation++;selected=game;board.replaceChildren();board.className='';document.querySelector('.game-surface').classList.remove('sudoku-surface');document.body.classList.remove('sudoku-mode');score.replaceChildren();say('');overview.hidden=true;play.hidden=false;
        const [title,category,instructions]=info[game];byId('game-title').textContent=title;byId('game-category').textContent=category;byId('instructions').textContent=instructions;
        ({pairs,words:scramble,tiles,sudoku,sequence,math,focus:colorFocus})[game]();byId('game-title').focus();
    }
    document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{opener=b;start(b.dataset.game);});
    byId('all-games').onclick=()=>{clearTimers();generation++;document.body.classList.remove('sudoku-mode');play.hidden=true;overview.hidden=false;board.replaceChildren();opener?.focus();};
    byId('new-game').onclick=()=>start(selected);
    byId('home').onclick=()=>{if(parent!==window)parent.postMessage({type:'oxypeak-chart-close'},location.origin);else if(history.length>1)history.back();else location.href='seat.html';};
    function pairs(){
        const symbols=[{name:'Dr. Mo',icon:'🧑‍⚕️'},{name:'HBOT',icon:'🫧'},{name:'Oxygen',icon:'O₂'},{name:'OxyPeak',icon:'💚'},{name:'Longevity',icon:'🧬'},{name:'Brain Power',icon:'🧠'},{name:'Vitality',icon:'🌱'},{name:'Good Vibes',icon:'☀️'}],deck=C.shuffle([...symbols,...symbols]);
        let opened=[],matched=0,locked=false,moves=0;chips('0 of 8 pairs','0 turns');const grid=element('div',undefined,'tile-grid');board.append(grid);
        deck.forEach((symbol,index)=>{const card=button('♡',()=>{
            if(locked||card.disabled||opened.some(x=>x.card===card))return;
            card.replaceChildren(element('span',symbol.icon,'pair-icon'),element('span',symbol.name,'pair-name'));card.classList.add('revealed');card.setAttribute('aria-label',symbol.name);opened.push({card,symbol,index});if(opened.length!==2)return;moves++;
            if(opened[0].symbol===opened[1].symbol){opened.forEach(x=>{x.card.disabled=true;x.card.classList.add('matched');});opened=[];matched++;say(matched===8?'All pairs found! A lovely bit of remembering.':'A match! Keep going.');}
            else{locked=true;later(()=>{opened.forEach(x=>{x.card.textContent='♡';x.card.classList.remove('revealed');x.card.setAttribute('aria-label','Card '+(x.index+1)+', face down');});opened=[];locked=false;},1100);}
            chips(matched+' of 8 pairs',moves+' turns');
        },'tile pair-card');card.setAttribute('aria-label','Card '+(index+1)+', face down');grid.append(card);});
    }
    function scramble(){
        const entry=nextWord(),answer=entry.word;let mixed=C.shuffle(answer).join('');if(mixed===answer)mixed=answer.slice(1)+answer[0];let won=false;
        chips(GameWords.length.toLocaleString()+' words',wordWins+' solved');board.append(element('p',entry.category,'hint'));
        const letters=element('div',undefined,'scramble');for(const letter of mixed)letters.append(element('span',letter,'letter'));board.append(letters);
        const form=element('form',undefined,'word-form'),input=element('input');input.setAttribute('aria-label','Your word');input.autocomplete='off';input.spellcheck=false;input.maxLength=answer.length;input.autocapitalize='characters';
        const check=button('Check word',()=>{},'primary');check.type='submit';form.append(input,check);form.onsubmit=e=>{e.preventDefault();if(won)return;if(input.value.trim().toUpperCase()===answer){won=true;wordWins++;chips(GameWords.length.toLocaleString()+' words',wordWins+' solved');say('You got it! Ready for another?');check.disabled=true;input.disabled=true;next.hidden=false;next.focus();}else say('Not quite. Try rearranging the letters, or ask for a hint.');};board.append(form);
        let hints=0;const hint=button('Hint',()=>{hints=Math.min(answer.length-1,hints+1);say('Starts with '+answer.slice(0,hints)+' · '+answer.length+' letters.');});
        const reveal=button('Reveal word',()=>{if(won)return;say('The word is '+answer+'. Try a fresh word when you’re ready.');check.disabled=true;input.disabled=true;hint.disabled=true;reveal.disabled=true;next.hidden=false;});
        board.append(controls(hint,button('Mix letters',()=>{const lettersNew=C.shuffle(mixed);letters.replaceChildren(...lettersNew.map(l=>element('span',l,'letter')));}),reveal));
        const next=button('Next word →',()=>start('words'),'primary next');next.hidden=true;board.append(next);
    }
    function tiles(){const values=C.slideBoard();let empty=values.indexOf(0),moves=0,won=false,suppressUntil=0;const grid=element('div',undefined,'tile-grid slide-grid');board.append(grid);chips('Tap or swipe · no typing','0 moves');
        function move(index){if(won||!C.neighbors(empty).includes(index)){say('Choose a highlighted tile directly beside the empty space.');return;}const value=values[index];[values[empty],values[index]]=[values[index],values[empty]];empty=index;moves++;won=values.every((n,j)=>n===(j+1)%16);render(value);chips('Tap or swipe · no typing',moves+' moves');say(won?'Perfect order! Solved in '+moves+' moves.':'Keep going: 1, 2, 3, 4 on the top row.');}
        function render(focusValue){grid.replaceChildren();values.forEach((value,index)=>{const legal=C.neighbors(empty).includes(index);const tile=button(value?String(value):'SPACE',()=>{if(Date.now()>suppressUntil)move(index);},'tile'+(!value?' slide-space':legal?' movable':''));tile.disabled=!value||won;tile.setAttribute('aria-label',value?'Tile '+value+(legal?', can move':''):'Empty space');let origin;
            tile.onpointerdown=e=>{origin={x:e.clientX,y:e.clientY};if(legal)tile.setPointerCapture(e.pointerId);};tile.onpointerup=e=>{if(!origin)return;const dx=e.clientX-origin.x,dy=e.clientY-origin.y;origin=null;if(Math.max(Math.abs(dx),Math.abs(dy))<15)return;suppressUntil=Date.now()+350;const direction=Math.abs(dx)>Math.abs(dy)?(dx>0?1:-1):(dy>0?4:-4);if(index+direction===empty&&legal)move(index);else say('Swipe toward the empty space, or tap a highlighted tile.');};tile.onpointercancel=()=>{origin=null;};
            grid.append(tile);if(value===focusValue&&!won)tile.focus();});}render();
        board.append(element('p','Goal: 1 2 3 4 / 5 6 7 8 / 9 10 11 12 / 13 14 15 □','hint'));
    }
    function sudoku(){chips('Choose difficulty');board.append(element('p','Classic 9 × 9 Sudoku, or a small starter grid.','hint'),controls(...[['Starter · 4 × 4','mini'],['Easy · 9 × 9','easy'],['Medium · 9 × 9','medium'],['Hard · 9 × 9','hard']].map(([label,level])=>button(label,()=>sudokuPlay(level),level==='medium'?'primary':''))));}
    function sudokuPlay(level){board.replaceChildren();document.querySelector('.game-surface').classList.add('sudoku-surface');document.body.classList.add('sudoku-mode');const {puzzle,solution,size,box}=C.sudoku(Math.random,level),values=[...puzzle];let selectedCell=-1,won=false;chips(level==='mini'?'Starter':level[0].toUpperCase()+level.slice(1),puzzle.filter(Boolean).length+' clues · one solution');byId('instructions').textContent='Use 1–'+size+' once in every row, column and '+box+' × '+box+' box. Tap a square, then choose a number.';
        const layout=element('div',undefined,'sudoku-layout'),grid=element('div',undefined,'sudoku-grid dynamic-sudoku'),pad=element('div',undefined,'number-pad'),cells=[];grid.style.setProperty('--size',size);pad.style.gridTemplateColumns='repeat('+box+',1fr)';
        function render(){cells.forEach((cell,i)=>{cell.textContent=values[i]||'·';cell.classList.toggle('selected',i===selectedCell);cell.setAttribute('aria-label','Row '+(Math.floor(i/size)+1)+', column '+(i%size+1)+', '+(values[i]||'empty'));});}
        function put(n){if(selectedCell<0||won){say('Choose an empty square first.');return;}values[selectedCell]=n;cells[selectedCell].classList.remove('wrong');render();if(values.every((v,i)=>v===solution[i])){won=true;say('Beautifully solved!');cells.forEach(c=>c.disabled=true);pad.querySelectorAll('button').forEach(b=>b.disabled=true);}}
        puzzle.forEach((v,i)=>{const cell=button(v||'·',()=>{selectedCell=i;render();say('Choose a number.');},'sudoku-cell');cell.disabled=Boolean(v);if(i%size%box===box-1&&i%size!==size-1)cell.style.borderRight='2px solid #718990';if(Math.floor(i/size)%box===box-1&&Math.floor(i/size)!==size-1)cell.style.borderBottom='2px solid #718990';cell.onkeydown=e=>{if(new RegExp('^[1-'+size+']$').test(e.key)){e.preventDefault();selectedCell=i;put(Number(e.key));}if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();selectedCell=i;put(0);}};cells.push(cell);grid.append(cell);});
        for(let n=1;n<=size;n++)pad.append(button(String(n),()=>put(n)));const erase=button('Erase',()=>put(0),'erase');erase.style.gridColumn=box===3?'span 2':'1 / -1';pad.append(erase,button('Check',()=>{let wrong=0;cells.forEach((c,i)=>{const invalid=values[i]!==0&&values[i]!==solution[i];c.classList.toggle('wrong',invalid);if(invalid)wrong++;});say(wrong?'Highlighted squares need another look.':'Looking good. Keep going!');}));layout.append(grid,pad);board.append(layout);render();
    }
    function sequence(){chips('Choose difficulty');board.append(controls(...[['Easy · 3 steps',1],['Medium · 5 steps',2],['Hard · 7 steps, reverse',3]].map(([label,level])=>button(label,()=>{sequenceLevel=level;sequencePlay();},level===2?'primary':''))));}
    function sequencePlay(){board.replaceChildren();
        const names=['Circle','Diamond','Triangle','Square'],shapes=['●','◆','▲','■'];let pattern=Array.from({length:sequenceLevel===1?3:sequenceLevel===2?5:7},()=>Math.floor(Math.random()*4)),position=0,accepting=false,playing=false,best=0;
        const grid=element('div',undefined,'memory-grid'),pads=[];const playButton=button('Start pattern',playPattern,'primary'),replay=button('Replay pattern',playPattern);replay.hidden=true;
        byId('instructions').textContent=sequenceLevel===3?'Hard mode: watch, then repeat the sequence in REVERSE order.':'Watch, then tap the same sequence. Each successful round adds a step.';chips(['','Easy','Medium','Hard · reverse'][sequenceLevel],pattern.length+' steps');names.forEach((name,i)=>{const pad=button('',()=>{
            if(!accepting)return;pad.classList.add('lit');later(()=>pad.classList.remove('lit'),180);
            if(i!==(sequenceLevel===3?[...pattern].reverse():pattern)[position]){accepting=false;pads.forEach(p=>p.disabled=true);say('Almost! Watch the same pattern and try again.');playButton.textContent='Try again';playButton.hidden=false;replay.hidden=true;return;}
            position++;if(position===pattern.length){accepting=false;best=Math.max(best,pattern.length);pads.forEach(p=>p.disabled=true);say('You remembered all '+pattern.length+' steps!');playButton.textContent='Next round →';playButton.onclick=()=>{pattern.push(Math.floor(Math.random()*4));playPattern();};playButton.hidden=false;replay.hidden=true;chips(['','Easy','Medium','Hard · reverse'][sequenceLevel],'Best: '+best+' steps');}else say(position+' of '+pattern.length+' steps');
        },'memory-pad');pad.append(element('span',shapes[i]),element('small',name));pad.setAttribute('aria-label',name);pad.disabled=true;pads.push(pad);grid.append(pad);});board.append(grid,controls(playButton,replay));
        async function playPattern(){if(playing)return;playing=true;accepting=false;position=0;const current=generation;playButton.hidden=true;playButton.onclick=playPattern;replay.hidden=true;pads.forEach(p=>{p.disabled=true;p.classList.remove('lit');});say('Watch the pattern…');chips('Level '+(pattern.length-1),pattern.length+' steps');await delay(350);
            for(const index of pattern){if(current!==generation)return;pads[index].classList.add('lit');await delay(sequenceLevel===1?650:sequenceLevel===2?430:280);pads[index].classList.remove('lit');await delay(sequenceLevel===3?130:180);}
            if(current!==generation)return;playing=false;accepting=true;pads.forEach(p=>p.disabled=false);replay.hidden=false;say(sequenceLevel===3?'Your turn. REVERSE the pattern.':'Your turn. Repeat the pattern.');
        }
    }
    function quizRound(kind){let round=0,correct=0;const seen=new Set();
        function next(){clearTimers();board.replaceChildren();say('');if(round===10){chips('10 rounds complete',correct+' correct');board.append(element('div',correct+' / 10','celebrate'),element('p',correct===10?'A perfect round. Nicely focused!':'Nice work. Every round is a fresh challenge.','hint'),button('Play another round',()=>start(kind),'primary next'));return;}
            round++;chips('Round '+round+' of 10',correct+' correct');const dots=element('div',undefined,'dots');for(let i=0;i<10;i++)dots.append(element('span',undefined,'dot'+(i<round?' done':'')));board.append(dots);
            let question,answer,choices;
            if(kind==='math'){let q;for(let tries=0;tries<25;tries++){q=C.mathQuestion(mathLevel);const key=q.a+q.symbol+q.b;if(!seen.has(key)){seen.add(key);break;}}question=element('div',q.a+' '+q.symbol+' '+q.b+' = ?','question');answer=q.answer;choices=q.choices;}
            else{const colors=[['Blue','#215db4'],['Green','#207346'],['Red','#be3943'],['Purple','#8045a4'],['Orange','#a9480c'],['Brown','#714c32']].slice(0,focusLevel===1?4:6),ink=Math.floor(Math.random()*colors.length),word=(ink+1+Math.floor(Math.random()*(colors.length-1)))%colors.length;const readWord=focusLevel===3&&Math.random()<.5;byId('instructions').textContent=readWord?'READ THE WORD — ignore its ink color.':'MATCH THE INK — ignore what the word spells.';question=element('div',colors[word][0].toUpperCase(),'question');question.style.color=colors[ink][1];answer=colors[readWord?word:ink][0];choices=C.shuffle(colors.map(c=>c[0]));}
            board.append(question);const answers=element('div',undefined,'answers'),buttons=[];let answered=false;const nextButton=button(round===10?'See results →':'Next challenge →',next,'primary next');nextButton.hidden=true;
            choices.forEach(value=>{const b=button(String(value),()=>{if(answered)return;answered=true;if(value===answer){correct++;say('That’s right!');}else say('The answer is '+answer+'. On to the next one.');buttons.forEach(({button,choice})=>{button.disabled=true;button.classList.toggle('correct',choice===answer);button.classList.toggle('incorrect',choice===value&&value!==answer);});chips('Round '+round+' of 10',correct+' correct');nextButton.hidden=false;nextButton.focus();});buttons.push({button:b,choice:value});answers.append(b);});board.append(answers,nextButton);if(kind==='focus'&&focusLevel>1){const seconds=focusLevel===3?4:7;chips('Round '+round+' of 10',correct+' correct',seconds+' seconds');later(()=>{if(answered)return;answered=true;buttons.forEach(({button,choice})=>{button.disabled=true;button.classList.toggle('correct',choice===answer);});say('Time’s up. The answer is '+answer+'.');nextButton.hidden=false;},seconds*1000);}
        }next();
    }
    function math(){chips('Choose your pace');board.append(element('p','Which challenge feels right today?','hint'),controls(...[['Gentle',1],['Balanced',2],['Stretch',3]].map(([label,level])=>button(label,()=>{mathLevel=level;quizRound('math');},level===mathLevel?'primary':''))));}
    function colorFocus(){chips('Choose difficulty');board.append(element('p','Hard mode switches between reading the word and matching the ink.','hint'),controls(...[['Easy · no timer',1],['Medium · 7 seconds',2],['Hard · 4 seconds + rule switches',3]].map(([label,level])=>button(label,()=>{focusLevel=level;quizRound('focus');},level===2?'primary':''))));}
    if('serviceWorker' in navigator)navigator.serviceWorker.register('offline-worker.js').catch(()=>{});
})();
